version: '2.4'

services:

  redis-cluster:
    tty: true
    build:
      context: .
      dockerfile: redis-cluster/Dockerfile
    hostname: server
    container_name: redis-cluster
    depends_on:
      - redis1
      - redis2
      - redis3
    mem_limit: 100m

  redis1:
    image: redis:6.2.5-alpine
    container_name: redis1
    volumes:
      - ./redis-cluster/redis-cluster1.tmpl:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
    command: redis-server /usr/local/etc/redis/redis.conf
    mem_limit: 100m
    environment:
      - TZ=Asia/Shanghai

  redis2:
    image: redis:6.2.5-alpine
    container_name: redis2
    volumes:
      - ./redis-cluster/redis-cluster2.tmpl:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
    command: redis-server /usr/local/etc/redis/redis.conf
    mem_limit: 100m
    environment:
      - TZ=Asia/Shanghai

  redis3:
    image: redis:6.2.5-alpine
    container_name: redis3
    volumes:
      - ./redis-cluster/redis-cluster3.tmpl:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
    command: redis-server /usr/local/etc/redis/redis.conf
    mem_limit: 100m
    environment:
      - TZ=Asia/Shanghai